spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: sora33
        loginPassword: sora33
mybatis-flex:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sora33?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl